name: Dependencies
on:
  push:
    paths:
      - Cargo.toml
      - Cargo.lock
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ github.token }}